"""create incident evidence table

Revision ID: 836894e065a6
Revises: cf996578486b
Create Date: 2026-06-25 20:16:46.618753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '836894e065a6'
down_revision: Union[str, Sequence[str], None] = 'cf996578486b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident_evidence', sa.Column('incident_id', sa.String(), nullable=False))
    op.add_column('incident_evidence', sa.Column('evidence_type', sa.String(), nullable=False))
    op.add_column('incident_evidence', sa.Column('source', sa.String(), nullable=False))
    op.add_column('incident_evidence', sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('incident_evidence', sa.Column('summary_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('incident_evidence', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'incident_evidence', 'incidents', ['incident_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incident_evidence', type_='foreignkey')
    op.drop_column('incident_evidence', 'created_at')
    op.drop_column('incident_evidence', 'summary_data')
    op.drop_column('incident_evidence', 'raw_data')
    op.drop_column('incident_evidence', 'source')
    op.drop_column('incident_evidence', 'evidence_type')
    op.drop_column('incident_evidence', 'incident_id')
    # ### end Alembic commands ###
