"""expand_incident_schema

Revision ID: cf996578486b
Revises: d71c52e07d60
Create Date: 2026-06-24 21:06:12.704846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf996578486b'
down_revision: Union[str, Sequence[str], None] = 'd71c52e07d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('alarm_name', sa.String(), nullable=False))
    op.add_column('incidents', sa.Column('service', sa.String(), nullable=False))
    op.add_column('incidents', sa.Column('region', sa.String(), nullable=False))
    op.add_column('incidents', sa.Column('metric_name', sa.String(), nullable=False))
    op.add_column('incidents', sa.Column('threshold', sa.Float(), nullable=False))
    op.add_column('incidents', sa.Column('current_value', sa.Float(), nullable=False))
    op.add_column('incidents', sa.Column('severity', sa.String(), nullable=False))
    op.add_column('incidents', sa.Column('source', sa.String(), nullable=False))
    op.add_column('incidents', sa.Column('status', sa.String(), nullable=False))
    op.add_column('incidents', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'created_at')
    op.drop_column('incidents', 'status')
    op.drop_column('incidents', 'source')
    op.drop_column('incidents', 'severity')
    op.drop_column('incidents', 'current_value')
    op.drop_column('incidents', 'threshold')
    op.drop_column('incidents', 'metric_name')
    op.drop_column('incidents', 'region')
    op.drop_column('incidents', 'service')
    op.drop_column('incidents', 'alarm_name')
    # ### end Alembic commands ###
